version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - file-storing-service
      - file-analysis-service

  file-analysis-service:
    build: ./file-analysis-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://file-analysis-db:5432/analysis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - file-analysis-data:/app/files
    depends_on:
      - file-storing-service
      - file-analysis-db

  file-storing-service:
    build: ./file-storing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://file-storing-db:5432/storing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - file-storing-data:/app/files
    depends_on:
      - file-storing-db

  file-analysis-db:
    image: postgres:15
    environment:
      POSTGRES_DB: analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - file-analysis-db-data:/var/lib/postgresql/data

  file-storing-db:
    image: postgres:15
    environment:
      POSTGRES_DB: storing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - file-storing-db-data:/var/lib/postgresql/data

volumes:
  file-analysis-data:
  file-storing-data:
  file-analysis-db-data:
  file-storing-db-data:
