server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway-Response, Hello from API Gateway
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
