server:
  port: 8082

spring:
  application:
    name: file-analysis-service
  datasource:
    url: jdbc:postgresql://postgres:5432/analysis
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

file:
  storage-location: app/wordclouds
